Finishing Up

diff --git a/.github/workflows/build_pre_release.yml b/.github/workflows/build_pre_release.yml
--- a/.github/workflows/build_pre_release.yml
+++ b/.github/workflows/build_pre_release.yml
@@ -71,20 +71,20 @@ jobs:
         run: |
           wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/youtube.ipa
 
-          file_type=$(file --mime-type -b ${{ github.workspace }}/youtube.ipa)
+          ipa_type=$(file --mime-type -b ${{ github.workspace }}/youtube.ipa)
 
-          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
-            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
+          if [[ "$ipa_type" != "application/x-ios-app" && "$ipa_type" != "application/zip" ]]; then
+            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $ipa_type."
             exit 1
           fi
-
-      - name: Get Youtube Version 
+ 
+      - name: Get YouTube Version 
         run: |
           mkdir -p ${{ github.workspace }}/ytversion
           cp -r ${{ github.workspace }}/youtube.ipa ${{ github.workspace }}/ytversion/youtube.ipa
           unzip -q ${{ github.workspace }}/ytversion/youtube.ipa -d ${{ github.workspace }}/ytversion/ytextracted
           echo "YT_VERSION=$(grep -A 1 '<key>CFBundleVersion</key>' ${{ github.workspace }}/ytversion/ytextracted/Payload/YouTube.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV
-          echo -e 'Done!'
+          echo -e 'Done! The YouTube Version is ${{ env.YT_VERSION }}'
 
       - name: Install Dependencies
         run: brew install make ldid swiftlint
@@ -119,6 +119,13 @@ jobs:
         run: |
           wget "${{ inputs.deb_url }}" --no-verbose -O ${{ github.workspace }}/ytlite.deb
 
+          deb_type=$(file --mime-type -b ${{ github.workspace }}/ytlite.deb)
+
+          if [[ "$deb_type" != "application/vnd.debian.binary-package" ]]; then
+            echo "::error::Validation failed: The downloaded file is not a valid deb. Detected type: $deb_type."
+            exit 1
+          fi
+
       - name: Get YTLite Version
         run: |
           cd ${{ github.workspace }}
@@ -126,7 +133,7 @@ jobs:
           tar -xzf control.tar.gz ./control
           VERSION=$(grep '^Version:' control | cut -d ' ' -f2)
           echo "YTLITE_VERSION=$VERSION" >> $GITHUB_ENV
-          echo -e 'Done!'
+          echo -e 'Done! The YTLite Version is ${{ env.YTLITE_VERSION }}'
 
       - name: Clone Open in YouTube (Safari Extension)
         run: |
@@ -421,7 +428,7 @@ jobs:
         if: ${{ inputs.draft_release }}
         uses: softprops/action-gh-release@v2.3.3
         with:
-          tag_name: ytliteplusextra-ipa${{ github.run_number }}
+          tag_name: ytliteplusextra-pre-release-ipa${{ github.run_number }}
           name: YTLitePlusEXTRA_${{ env.YT_VERSION }}_v${{ env.YTLITE_VERSION }} (${{ github.run_number }}) 
           files: YTLitePlusEXTRA_${{ env.YT_VERSION }}_v${{ env.YTLITE_VERSION }}.ipa
           draft: true
